#!/usr/bin/env bash

rm -rf tmp/public.building tmp/public.old
mkdir -p tmp/public.building
cp -R vendor/WordPress/WordPress/* tmp/public.building
cp -R public/* tmp/public.building
touch public.built
mv public.built tmp/public.old && mv tmp/public.building public.built
rm -rf tmp/public.old
cp -R public/* public.built
cp public/.htaccess public.built/.htaccess
